def aarch64PodTemplate = """
        apiVersion: v1
        kind: Pod
        spec:
          containers:
          - name: centos7
            image: centos:7
            # image: system.registry.ssre.wrstudio.cloud/test-images/wrstudio-content-installer:1.1.5
            # image: arm64v8/nginx
            command:
            - cat
            tty: true
            resources:
              limits:
                cpu: 0.6
                memory: 2.5Gi
          imagePullSecrets:
            - name: dockerhub
          # nodeSelector:
          #   kubernetes.io/arch: arm64
          #   kubernetes.io/os: linux
          tolerations:
          - key: "spotInstance"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
          - key: "cpu"
            operator: "Equal"
            value: "arm"
            effect: "NoSchedule"
      """.stripIndent().trim()

pipeline {
  parameters {
    string(name: 'PLUGIN_NAME', description: 'Name of a plugin to build')
    string(name: 'PLUGIN_PATH', description: 'Path where the plugin project content is located')
  }

  agent {
    kubernetes {
      yaml "${aarch64PodTemplate}"
    }
  }

  options {
    disableConcurrentBuilds()
    buildDiscarder(logRotator(numToKeepStr:'10'))
    timeout(time: 60, unit: 'MINUTES')
  }

  stages {
    stage("Setup"){
      steps{
        container('centos7'){
          sh """
          set +e
          yum install -y wget
          python3 -m venv ${WORKSPACE}/${PLUGIN_PATH}/env_centos7
          ${WORKSPACE}/${PLUGIN_PATH}/env_centos7/bin/pip install pip==19.3.1 wheel tox
          ${WORKSPACE}/${PLUGIN_PATH}/env_centos7/bin/pip install https://github.com/cloudify-cosmo/wagon/archive/refs/heads/master.zip
          uname -a
          uname -r -v -p
          cat /etc/issue
          cat /etc/redhat-release
          arch
          """
        }
      }
    }
  }
}
